### ISSUE TITLE
Ignore files define in `.gitignore`

### ISSUE THREAD

**Issue by flybayer** [prisma/codemods#4]
Currently the codemod runs on all code in a project, even huge cache directories ignored by git.

Codemod should ignore any files ignored by git.

**Comment by williamluke4** [comment]
Hi @flybayer, This logic is already present. Weird that it is not working. Could you try again using `0.5.3` and share the command that was executed. E.g 
```
Executing command: jscodeshift --dry --verbose=2 --ignore-config=/home/will/Prisma/nextjs-blog/.gitignore --ignore-pattern=**/node_modules/** --extensions=tsx,ts,js,tsx --parser=tsx --transform /home/will/Prisma/namespace-codemode/transforms/to$.js /home/will/Prisma/nextjs-blog/
```

**Comment by williamluke4** [comment]
Feel free to reopen if it is not fixed

**Comment by cheburan** [comment]
This issue is still present (kind of) in the latest version ( at least for me). Have a `.gitignore` file with node_modules that is recognised by git but not by codemods.  

It works with the absolute path to the project (omits node_modules), but once the relative path is used, it bypaths `.gitignore`.

```
$ npx @prisma/codemods namespace ../../node-app/backend/ -d
```
